version: 2

references:
  defaults: &defaults
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/sugarshin.net
  configure_git: &configure_git
    name: Configure Git
    command: |
      git config --global user.name 'CircleCI'
      git config --global user.email 's+circleci@sugarshin.net'
  restore_yarn_cache: &restore_yarn_cache
    name: Restoring Cache - yarn
    keys:
      - comuque-frontend-yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - comuque-frontend-yarn-v1-{{ .Branch }}-
  save_yarn_cache: &save_yarn_cache
    key: comuque-frontend-yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - ./node_modules

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run:
          name: Install dependencies
          command: yarn
      - save_cache: *save_yarn_cache
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Tests
          command: yarn test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: *configure_git
      - run:
          name: Deploy
          command: |
            NODE_ENV=production npm run build
            node_modules/.bin/ts-node scripts/favicon.ts
            echo sugarshin.net > build/CNAME
            /bin/bash scripts/deploy.sh

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
