version: 2

references:
  defaults: &defaults
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/sugarshin.net
  configure_git: &configure_git
    name: Configure Git
    command: |
      git config --global user.name 'CircleCI'
      git config --global user.email 's+circleci@sugarshin.net'
  restore_npm_cache: &restore_npm_cache
    name: Restoring npm Cache
    keys:
      - npm-v1-{{ checksum "package-lock.json" }}
      - npm-v1-
  save_npm_cache: &save_npm_cache
    name: Saving npm Cache
    key: npm-v1-{{ checksum "package-lock.json" }}
    paths:
      - ~/sugarshin.net/node_modules

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_npm_cache
      - run:
          name: Install dependencies
          command: npm install
      - save_cache: *save_npm_cache
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_npm_cache
      - run:
          name: Install dependencies
          command: npm install
      - save_cache: *save_npm_cache
      - run:
          name: Build
          command: NODE_ENV=production npm run generate
      - persist_to_workspace:
          root: build
          paths: .
      - store_artifacts:
          path: build
          destination: build

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/sugarshin.net/build
      - run: *configure_git
      - run:
          name: Deploy
          command: /bin/bash scripts/deploy.bash

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
