name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run generate
        env:
          NODE_ENV: production
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - uses: actions/upload-artifact@v2
        with:
          name: .nuxt
          path: .nuxt
  deploy:
    runs-on: ubuntu-18.04
    needs: [test, build]
    steps:
      - uses: actions/checkout@v2
        if: github.ref == 'refs/heads/master'
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: build
          path: build
      - uses: ./.github/actions/deploy
        if: github.ref == 'refs/heads/master'
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GIT_URL: git@github.com:sugarshin/sugarshin.net.git
          BRANCH: gh-pages
          GITHUB_SHA: ${{ github.sha }}
          BUILD: build
