name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
        with:
          version: ${{ env.BIOME_VERSION }}
        env:
          BIOME_VERSION: 2.5.3
      - run: biome ci
  build:
    uses: ./.github/workflows/build.yml
