name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
        with:
          version: ${{ env.BIOME_VERSION }}
        env:
          BIOME_VERSION: 2.5.6
      - run: biome ci
  build:
    uses: ./.github/workflows/build.yml
